import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

function useOptimizeAB(experimentId) {
  const [variant, setVariant] = useState();
  useEffect(() => {
    window.dataLayer.push({ event: "optimize.activate" });
    let interval = setInterval(() => {
      console.log("windows => ", window.google_optimize);
      if (window.google_optimize !== undefined) {
        console.log("experimentId => ", experimentId);
        const variant = window.google_optimize.get(experimentId);
        console.log("variant => ", variant);
        if (typeof variant !== "undefined") setVariant(Number(variant));
        clearInterval(interval);
      }

      //get all experiments:
      console.log("experiments", window.gaData["UA-198905767-1"].experiments);
      Object.keys(window.gaData["UA-198905767-1"].experiments).forEach(
        function (key, index) {
          var value = window.gaData["UA-198905767-1"].experiments[key];
          console.log("Info", key, value, index);
        }
      );
    }, 3000);
  }, []);
  return variant;
}

export default function Home() {
  // ... then in _app.js you can use the variant for whatever
  const variant = useOptimizeAB("Z8IfX7lLSGm7PWNXZmrUvg");
  console.log("variant: ", variant);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,800;1,300;1,400;1,600;1,800&display=swap" rel="stylesheet"/>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=UA-198905767-1"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments)}
                  gtag('js', new Date());
                  gtag('config', 'UA-198905767-1', { optimize_id: 'OPT-TQ7N4PM'});
              `,
          }}
        ></script>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
